/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import utils.ConnectionFactory;
import static elemento.Elemento.log;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Donatarias extends javax.swing.JFrame {
    
    private ConnectionFactory cf;
    private int idEmisor, idDonataria;
    private boolean insert;
    
    public Donatarias(int idEmisor) {
        cf = new ConnectionFactory(log);
        this.idEmisor = idEmisor;
        initComponents();
        this.setLocationRelativeTo(null);
        consultarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaAuto = new com.toedter.calendar.JDateChooser();
        noAuto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        guardarDonat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fechaAuto.setDateFormatString("yyyy-MM-dd");

        jLabel2.setText("No. Autorizacion SAT");

        jLabel1.setText("Fecha de Autorizacion");

        guardarDonat.setText("Guardar");
        guardarDonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDonatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(guardarDonat, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardarDonat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarDonatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDonatActionPerformed
        // TODO add your handling code here:
        Connection con = elemento.Elemento.odbc();
        PreparedStatement stmt;
        
        try {
            if(insert){
                stmt = con.prepareStatement("INSERT INTO Donatarias (idEmisor,fechaAuto,noAuto) VALUES (?,?,?)");
                stmt.setInt(1, idEmisor);
                stmt.setDate(2, new java.sql.Date(fechaAuto.getDate().getTime()));
                stmt.setString(3, noAuto.getText().trim());
            }else{
                stmt = con.prepareStatement("UPDATE Donatarias SET fechaAuto = ?, noAuto = ? WHERE idDonataria = ?");
                stmt.setDate(1, new java.sql.Date(fechaAuto.getDate().getTime()));
                stmt.setString(2, noAuto.getText().trim());
                stmt.setInt(3, idDonataria);
            }
            JOptionPane.showMessageDialog(null, "Informacion guardada correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
            stmt.executeUpdate();
            stmt.close();
            con.close();
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            log.error("Error al guardar las donatarias: ",e);
            JOptionPane.showMessageDialog(null, "Ocurrio un error al guardar: " + e.getMessage(), "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarDonatActionPerformed

    private void consultarInfo(){
        Connection con = elemento.Elemento.odbc();
        Statement stmt = cf.stmtEscritura(con);
        ResultSet rs;
        
        try {
            rs = stmt.executeQuery("SELECT idDonataria, fechaAuto, noAuto FROM Donatarias WHERE idEmisor = " + idEmisor);
            if(rs.next()){
                idDonataria = rs.getInt("idDonataria");
                fechaAuto.setDate(rs.getDate("fechaAuto"));
                noAuto.setText(rs.getString("noAuto"));
                insert = false;
            }else{
                insert = true;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            log.error("Error al consultar las donatarias: ",e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donatarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donatarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donatarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donatarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donatarias(new Integer(args[0])).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechaAuto;
    private javax.swing.JButton guardarDonat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField noAuto;
    // End of variables declaration//GEN-END:variables
}
