/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import elemento.ConnectionFactory;
import elemento.Elemento;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abe
 */
public class Emisores_X extends javax.swing.JFrame {

    boolean modificar;
    int id;
    String rfce;
    List<String> listaEstados = new ArrayList();
    ConnectionFactory factory = new ConnectionFactory();
    
    public Emisores_X() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Emisores_X(boolean modificar,String rfce){
        this.modificar = modificar;
        this.rfce = rfce;
        initComponents();
        setLocationRelativeTo(null);
        llenarFormulario();
    }
    
    private void llenarFormulario(){
        Connection con = Elemento.odbc();
        Statement stmt = factory.stmtLectura(con);
        ResultSet rs;
        try{
            rs = stmt.executeQuery("SELECT * FROM Emisores WHERE rfc like \'"+rfce+"\'");
            if(rs.next()){
                id = rs.getInt("id");
                nombre.setText(rs.getString("nombre").trim());
                rfc.setText(rs.getString("rfc").trim());
                calle.setText(rs.getString("calle").trim());
                noExterior.setText(rs.getString("noExterior").trim());
                noInterior.setText(rs.getString("noInterior").trim());
                colonia.setText(rs.getString("colonia").trim());
                localidad.setText(rs.getString("localidad").trim());
                municipio.setText(rs.getString("municipio").trim());
                pais.setSelectedItem(rs.getString("pais"));
                estado.setSelectedItem(rs.getString("estado"));
                cp.setText(rs.getString("cp").trim());
                email.setText(rs.getString("email").trim());
                pass.setText(rs.getString("pass").trim());
            }
            rs.close();
            stmt.close();
            con.close();
        }catch(Exception ex){
            ex.printStackTrace();
            Elemento.log.error("Excepcion al consultar el emisor con el RFC: " + rfce + " : " + ex.getMessage() + " || " + ex.getCause().getMessage(),ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        noInterior = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        noExterior = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        municipio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        localidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        colonia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rfc = new javax.swing.JTextField();
        cp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        calle = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        pais = new javax.swing.JComboBox();
        estado = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Colonia");

        noInterior.setText("_");

        jLabel5.setText("No. Interior");

        jLabel4.setText("No. Exterior");

        jLabel9.setText("País");

        localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadActionPerformed(evt);
            }
        });

        jLabel8.setText("Municipio");

        jLabel7.setText("Localidad");

        jLabel1.setText("Nombre");

        jLabel10.setText("Estado");

        jLabel11.setText("C.P.");

        jLabel2.setText("RFC");

        jLabel3.setText("Calle");

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        borrar.setText("Limpiar Pantalla");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jLabel12.setText("e-mail");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel13.setText("Contraseña: ");

        pais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mexico", "Pais Extranjero" }));
        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });

        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Estado", "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Distrito Federal", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));

        jButton1.setText("Borrar Emisor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(noExterior, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addComponent(colonia)
                                    .addComponent(localidad)
                                    .addComponent(municipio)
                                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(guardar)
                        .addGap(18, 18, 18)
                        .addComponent(borrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(noExterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(noInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(cancelar)
                    .addComponent(borrar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        Connection con = Elemento.odbc();
        Statement stmt = factory.stmtEscritura(con);
        try{
            String query, textoLog;
            if(modificar){
                query = "UPDATE Emisores SET nombre=\'"+nombre.getText().trim()+"\',rfc=\'"+rfc.getText().trim()+"\',calle=\'"+calle.getText().trim()+"\',"
                        + "noExterior=\'"+noExterior.getText().trim()+"\',noInterior=\'"+noInterior.getText().trim()+"\',colonia=\'"+colonia.getText().trim()+"\',"
                        + "localidad=\'"+localidad.getText().trim()+"\',municipio=\'"+municipio.getText().trim()+"\',estado=\'"+estado.getSelectedItem().toString().trim()+"\',"
                        + "pais=\'"+pais.getSelectedItem().toString().trim()+"\',cp=\'"+cp.getText().trim()+"\',pass=\'"+String.copyValueOf(pass.getPassword()).trim()+ "\',"
                        + "email=\'"+ email.getText().trim() +"\' WHERE id="+id;
                textoLog = "El emisor " + nombre.getText() + " fue actualizado correctamente";
            }else{
                query = "INSERT INTO Emisores (nombre,rfc,calle,noExterior,noInterior,colonia,localidad,municipio,estado,pais,cp,pass,email) "
                    + "VALUES (\'"+nombre.getText().trim()+"\',\'"+rfc.getText().trim()+"\',\'"+calle.getText().trim()+"\',\'"+noExterior.getText().trim()+"\',"
                    + "\'"+noInterior.getText().trim()+"\',\'"+colonia.getText().trim()+"\',\'"+localidad.getText().trim()+"\',\'"+municipio.getText().trim()+"\',"
                    + "\'"+estado.getSelectedItem().toString().trim()+"\',\'"+pais.getSelectedItem().toString().trim()+"\',\'"+cp.getText().trim()+"\',\'" + String.copyValueOf(pass.getPassword()).trim() + "\',"
                    + "\'"+ email.getText().trim() +"\')";
                textoLog = "El emisor " + nombre.getText() + " fue agregado correctamente";
            }
            stmt.execute(query);
            JOptionPane.showMessageDialog(null, textoLog);
            Elemento.log.info(textoLog);
            stmt.close();
            con.close();
            this.dispose();
        }catch(SQLException e){
            e.printStackTrace();
            String msg = "Excepcion: No se pudo agregar al emisor a la base de datos: " + e.getLocalizedMessage();
            Elemento.log.error(msg,e);
            JOptionPane.showMessageDialog(null, msg);
        }catch(Error err){
            err.printStackTrace();
            String msg = "Error: No se pudo agregar al emisor a la base de datos: " + err.getLocalizedMessage();
            Elemento.log.error(msg,err);
            JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        borrarTodo();

    }//GEN-LAST:event_borrarActionPerformed
    
    private void borrarTodo(){
        nombre.setText("");
        rfc.setText("");
        calle.setText("");
        noExterior.setText("");
        noInterior.setText("");
        colonia.setText("");
        localidad.setText("");
        municipio.setText("");
        estado.setSelectedIndex(0);
        pais.setSelectedIndex(0);
        cp.setText("");
        email.setText("");
        rfc.transferFocusBackward();
    }

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void localidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadActionPerformed

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel combo = (DefaultComboBoxModel) estado.getModel();
        
        if(listaEstados.isEmpty()){
            for (int i = 0; i < combo.getSize(); i++) {
                listaEstados.add(combo.getElementAt(i).toString());
            }
        }
        
        if(pais.getSelectedIndex() > 0){
            combo.removeAllElements();
            combo.addElement("Estado Extranjero");
        }else{
            combo.removeAllElements();
            for (int i = 0; i < listaEstados.size(); i++) {
                combo.addElement(listaEstados.get(i));
            }
        }
    }//GEN-LAST:event_paisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       int opc = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar este emisor?","Eliminar Emisor",JOptionPane.YES_NO_OPTION);
       switch(opc){
           case JOptionPane.YES_OPTION:
               borrarEmisor();
               break;
           case JOptionPane.NO_OPTION:
               break;
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void borrarEmisor(){
        Connection con = Elemento.odbc();
        Statement stmt = factory.stmtEscritura(con);
        
        try{
            stmt.executeUpdate("DELETE FROM Emisores WHERE id = "+id);
            JOptionPane.showMessageDialog(null, "El Emisor " + nombre.getText() + " fue eliminado correctamente");
            stmt.close();
            con.close();
            this.dispose();
        }catch(SQLException | HeadlessException ex){
            ex.printStackTrace();
            Elemento.log.error("Excepcion al eliminar un emisor: " + ex.getMessage(),ex);
            JOptionPane.showMessageDialog(null, "Excepcion al eliminar un emisor: " + ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emisores_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emisores_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emisores_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emisores_X.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    public javax.swing.JTextField calle;
    private javax.swing.JButton cancelar;
    public javax.swing.JTextField colonia;
    public javax.swing.JTextField cp;
    private javax.swing.JTextField email;
    public javax.swing.JComboBox estado;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField localidad;
    public javax.swing.JTextField municipio;
    public javax.swing.JTextField noExterior;
    public javax.swing.JTextField noInterior;
    public javax.swing.JTextField nombre;
    public javax.swing.JComboBox pais;
    private javax.swing.JPasswordField pass;
    public javax.swing.JTextField rfc;
    // End of variables declaration//GEN-END:variables
}
