/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nominas;

import elemento.Elemento;
import elemento.Factura;
import elemento.Layout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abe
 */
public class Nominas extends javax.swing.JFrame {
    boolean continuar;
    public boolean seguir = true;
    Percepciones per;
    Deducciones dec;
    complementos.nominas.Empleado emp;
    complementos.nominas.Nominas nomi;
    String nombreEmpleado, rfcEmpleado;
    nominas.Empleado empleado;
    Factura fact;
    
    public Percepciones getPer() {
        return per;
    }

    public Deducciones getDec() {
        return dec;
    }
    
    public Nominas(Factura fact,Empleado emp, String nombreEmpleado, String rfcEmpleado) {
        initComponents();
        this.setLocationRelativeTo(null);
        per = new Percepciones(emp.getIdEmpleado(),true);
        dec = new Deducciones(emp.getIdEmpleado(),true);
        this.emp = emp.getEmpleado();
        this.empleado = emp;
        
        if(emp.getFechaInicialRelLaboral() != null)
            antiguedad.setText(""+calcularAntiguedadSemanas(emp.getFechaInicialRelLaboral()));
        else
            antiguedad.setText("0");
        
        this.nombreEmpleado = nombreEmpleado;
        this.rfcEmpleado = rfcEmpleado;
        labelNombre.setText(nombreEmpleado);
        labelRfc.setText(rfcEmpleado);
        numEmpleado.setText(""+emp.getNumEmpleado());
        this.fact = fact;
    }
    
    private void crearLayoutNomina(complementos.nominas.Nominas nomi){
        Layout layout = new Layout (fact,empleado,nomi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numEmpleado = new javax.swing.JTextField();
        numDiasPagados = new javax.swing.JTextField();
        tipoRegimen = new javax.swing.JComboBox();
        antiguedad = new javax.swing.JTextField();
        fechaPago = new com.toedter.calendar.JDateChooser();
        fechaInicialPago = new com.toedter.calendar.JDateChooser();
        fechaFinalPago = new com.toedter.calendar.JDateChooser();
        percepcionesBox = new javax.swing.JCheckBox();
        deduccionesBox = new javax.swing.JCheckBox();
        verPercepciones = new javax.swing.JButton();
        verDeducciones = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        labelRfc = new javax.swing.JLabel();
        incapacidad = new javax.swing.JCheckBox();
        horasExtra = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        diasIncapacidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tipoIncapacidad = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        descuentoIncapacidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dias = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tipoHoras = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cantidadHorasExtra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        importePagado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Numero de Empleado");

        jLabel4.setText("Tipo de Regimen");

        jLabel6.setText("Fecha de Pago");

        jLabel7.setText("Fecha Inicial de Pago");

        jLabel8.setText("Fecha Final de Pago");

        jLabel9.setText("Numero de dias Pagados");

        jLabel14.setText("Antigüedad (Semanas)");

        numDiasPagados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numDiasPagadosFocusGained(evt);
            }
        });

        tipoRegimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asimilados a salarios", "Sueldos y salarios", "Jubilados", "Pensionados" }));

        fechaPago.setDateFormatString("yyyy-MM-dd");

        fechaInicialPago.setDateFormatString("yyyy-MM-dd");

        fechaFinalPago.setDateFormatString("yyyy-MM-dd");
        fechaFinalPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fechaFinalPagoFocusLost(evt);
            }
        });
        fechaFinalPago.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fechaFinalPagoInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                fechaFinalPagoCaretPositionChanged(evt);
            }
        });

        percepcionesBox.setText("Percepciones");
        percepcionesBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                percepcionesBoxStateChanged(evt);
            }
        });
        percepcionesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percepcionesBoxActionPerformed(evt);
            }
        });

        deduccionesBox.setText("Deducciones");
        deduccionesBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deduccionesBoxStateChanged(evt);
            }
        });

        verPercepciones.setText("Ver Percepciones");
        verPercepciones.setEnabled(false);
        verPercepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPercepcionesActionPerformed(evt);
            }
        });

        verDeducciones.setText("Ver Deducciones");
        verDeducciones.setEnabled(false);
        verDeducciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDeduccionesActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        labelNombre.setText("jLabel1");

        labelRfc.setText("jLabel3");

        incapacidad.setText("Incapacidad");
        incapacidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                incapacidadStateChanged(evt);
            }
        });

        horasExtra.setText("Horas Extra");
        horasExtra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                horasExtraStateChanged(evt);
            }
        });

        jLabel5.setText("Dias de Incapacidad");

        diasIncapacidad.setEnabled(false);

        jLabel10.setText("Tipo de Incapacidad");

        tipoIncapacidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1, Riesgo de trabajo", "2, Enfermedad en general", "3, Maternidad" }));
        tipoIncapacidad.setEnabled(false);

        jLabel11.setText("Descuento");

        descuentoIncapacidad.setEnabled(false);

        jLabel12.setText("Dias");

        dias.setEnabled(false);

        jLabel13.setText("Tipo de Horas");

        tipoHoras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dobles", "Triples" }));
        tipoHoras.setEnabled(false);

        jLabel15.setText("Horas Extra");

        cantidadHorasExtra.setEnabled(false);

        jLabel16.setText("Importe Pagado");

        importePagado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoRegimen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaInicialPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaFinalPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numDiasPagados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(antiguedad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(percepcionesBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deduccionesBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(verPercepciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(verDeducciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diasIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descuentoIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(incapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dias)))))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cantidadHorasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(importePagado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(labelRfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(percepcionesBox)
                            .addComponent(verPercepciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deduccionesBox)
                            .addComponent(verDeducciones))
                        .addGap(18, 18, 18)
                        .addComponent(incapacidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(diasIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tipoIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(descuentoIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(horasExtra))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fechaInicialPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fechaFinalPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numDiasPagados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(antiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cantidadHorasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(importePagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelar)
                            .addComponent(guardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRfc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        switch(JOptionPane.showConfirmDialog(null, "Esta seguro que desea cancelar?\nSe borraran todos los datos y el comprobante no se timbrara", "Desea cancelar?", JOptionPane.YES_NO_OPTION)){
            case JOptionPane.YES_OPTION:
                continuar = false;
                this.dispose();
                break;
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void percepcionesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percepcionesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percepcionesBoxActionPerformed

    private void percepcionesBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_percepcionesBoxStateChanged
        // TODO add your handling code here:
        if(percepcionesBox.isSelected()){
            verPercepciones.setEnabled(true);
        }else{
            verPercepciones.setEnabled(false);
        }
    }//GEN-LAST:event_percepcionesBoxStateChanged

    private void deduccionesBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deduccionesBoxStateChanged
        // TODO add your handling code here:
        if(deduccionesBox.isSelected()){
            verDeducciones.setEnabled(true);
        }else{
            verDeducciones.setEnabled(false);
        }
    }//GEN-LAST:event_deduccionesBoxStateChanged

    private void verPercepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPercepcionesActionPerformed
        // TODO add your handling code here:
        per.setVisible(true);
    }//GEN-LAST:event_verPercepcionesActionPerformed

    private void verDeduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDeduccionesActionPerformed
        // TODO add your handling code here:
        dec.setVisible(true);
    }//GEN-LAST:event_verDeduccionesActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // Codigo para guardar la nomina en el XML  
        nomi = new complementos.nominas.Nominas();
        complementos.nominas.Deducciones dedu = new complementos.nominas.Deducciones();
        complementos.nominas.Percepciones perc = new complementos.nominas.Percepciones();
        complementos.nominas.HorasExtra horas;
        complementos.nominas.Incapacidad inca;
        
        nomi.setEmpleado(emp);
        
        //Seteamos datos de nomina
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        nomi.setFechaPago(format.format(fechaPago.getDate()));
        nomi.setFechaInicialPago(format.format(fechaInicialPago.getDate()));
        nomi.setFechaFinalPago(format.format(fechaFinalPago.getDate()));
        nomi.setAntiguedad(new Integer(antiguedad.getText()));
        nomi.setNumDiasPagados(new Double(numDiasPagados.getText()));
        nomi.setRegistroPatronal("");
        
        //Seteamos deducciones
        dedu.setDeducciones(getDeducciones());
        dedu.setTotalExento(dec.getTotalExento());
        dedu.setTotalGravado(dec.getTotalGravado());
        nomi.setDeducciones(dedu);
        
        //Seteamos percepciones
        perc.setPercepciones(getPercepciones());
        perc.setTotalExento(per.getTotalExento());
        perc.setTotalGravado(per.getTotalGravado());
        nomi.setPercepciones(perc);
        
        //Seteamos incapacidad
        if(incapacidad.isSelected()){
            inca = new complementos.nominas.Incapacidad();
            inca.setDescuento(new Double(descuentoIncapacidad.getText().trim()));
            inca.setDiasIncapacidad(new Integer(diasIncapacidad.getText().trim()));
            inca.setTipoIncapacidad(""+(tipoIncapacidad.getSelectedIndex()+1));
            nomi.setIncapacidad(inca);
        }
        
        //Seteamos horas extra
        if(horasExtra.isSelected()){
            horas = new complementos.nominas.HorasExtra();
            horas.setDias(new Integer(dias.getText().trim()));
            horas.setHorasExtra(new Integer(cantidadHorasExtra.getText().trim()));
            horas.setImportePagado(new Double(importePagado.getText().trim()));
            horas.setTipoHoras(tipoHoras.getSelectedItem().toString());
            nomi.setHorasExtra(horas);
        }
        
        double des = 0;
        double isR = 0;
        for (int i = 0; i < nomi.getDeducciones().getDeducciones().size(); i++) {
            if(!nomi.getDeducciones().getDeducciones().get(i).getTipoDeduccion().equals("002")){
                des += nomi.getDeducciones().getDeducciones().get(i).getImporteGravado() + nomi.getDeducciones().getDeducciones().get(i).getImporteExento();
            }else{
                isR = nomi.getDeducciones().getDeducciones().get(i).getImporteExento()+nomi.getDeducciones().getDeducciones().get(i).getImporteGravado();
            }
        }
        
        fact.isrRetenido = isR;
        fact.descuento = Math.rint(des*100)/100;
        double to = fact.subtotal - fact.descuento - fact.isrRetenido;
        fact.total = Math.rint(to*100)/100;
        
        per.dispose();
        dec.dispose();
        seguir = false;
        this.crearLayoutNomina(nomi);
        this.setVisible(false);
    }//GEN-LAST:event_guardarActionPerformed

    public complementos.nominas.Nominas getNomina() {
        return nomi;
    }

    private List<complementos.nominas.Deducciones.Deduccion> getDeducciones(){
        DefaultTableModel model = (DefaultTableModel)dec.tabla.getModel();
        List<complementos.nominas.Deducciones.Deduccion> lista = new ArrayList();
        complementos.nominas.Deducciones.Deduccion ded;
        complementos.nominas.Deducciones dedus = new complementos.nominas.Deducciones();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            ded = dedus.getClase();
            ded.setTipoDeduccion(model.getValueAt(i, 0).toString());
            ded.setClave(model.getValueAt(i, 1).toString());
            ded.setConcepto(model.getValueAt(i, 2).toString());
            ded.setImporteGravado(new Double(model.getValueAt(i, 3).toString()));
            ded.setImporteExento(new Double(model.getValueAt(i, 4).toString()));
            
            lista.add(ded);
        }
        
        return lista;
    }
    
    private List<complementos.nominas.Percepciones.Percepcion> getPercepciones(){
        DefaultTableModel model = (DefaultTableModel)per.tabla.getModel();
        List<complementos.nominas.Percepciones.Percepcion> lista = new ArrayList();
        complementos.nominas.Percepciones.Percepcion perc;
        complementos.nominas.Percepciones percep = new complementos.nominas.Percepciones();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            perc = percep.getClase();
            perc.setTipoPercepcion(model.getValueAt(i, 0).toString());
            perc.setClave(model.getValueAt(i, 1).toString());
            perc.setConcepto(model.getValueAt(i, 2).toString());
            perc.setImporteGravado(new Double(model.getValueAt(i, 3).toString()));
            perc.setImporteExento(new Double(model.getValueAt(i, 4).toString()));
            
            lista.add(perc);
        }
        
        return lista;
    }
    
    private void fechaFinalPagoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fechaFinalPagoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFinalPagoCaretPositionChanged

    private void fechaFinalPagoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fechaFinalPagoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFinalPagoInputMethodTextChanged

    private void fechaFinalPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaFinalPagoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFinalPagoFocusLost

    private void numDiasPagadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numDiasPagadosFocusGained
        // TODO add your handling code here:
        numDiasPagados.setText(""+calcularDiasPagados(fechaInicialPago.getDate(),fechaFinalPago.getDate()));
    }//GEN-LAST:event_numDiasPagadosFocusGained

    private void incapacidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_incapacidadStateChanged
        // TODO add your handling code here:
        if(incapacidad.isSelected()){
            diasIncapacidad.setEnabled(true);
            tipoIncapacidad.setEnabled(true);
            descuentoIncapacidad.setEnabled(true);
        }else{
            diasIncapacidad.setEnabled(false);
            tipoIncapacidad.setEnabled(false);
            descuentoIncapacidad.setEnabled(false);
        }
    }//GEN-LAST:event_incapacidadStateChanged

    private void horasExtraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_horasExtraStateChanged
        // TODO add your handling code here:
        if(horasExtra.isSelected()){
            dias.setEnabled(true);
            cantidadHorasExtra.setEnabled(true);
            tipoHoras.setEnabled(true);
            importePagado.setEnabled(true);
        }else{
            dias.setEnabled(false);
            cantidadHorasExtra.setEnabled(false);
            tipoHoras.setEnabled(false);
            importePagado.setEnabled(false);
        }
    }//GEN-LAST:event_horasExtraStateChanged

    public long calcularDiasPagados(Date date, Date date2){
        try {
            java.util.GregorianCalendar cal = new java.util.GregorianCalendar(date.getYear(),date.getMonth(),date.getDate());
            java.util.GregorianCalendar cal2 = new java.util.GregorianCalendar(date2.getYear(),date2.getMonth(),date2.getDate());
            
            long difms = cal2.getTimeInMillis() - cal.getTimeInMillis();
            long difd = difms / (1000 * 60 * 60 * 24)+1;
            return difd;
        } catch (Exception ex) {
            ex.printStackTrace();
            Elemento.log.error("Excepcion al calcular los dias pagados: ",ex );
            return -1;
        }
    }
    
    public final long calcularAntiguedadSemanas(Date fechaInicial){
        try {
            Date date = fechaInicial;
            Date date2 = new Date();
            GregorianCalendar cal = new GregorianCalendar(date.getYear(),date.getMonth(),date.getDate());
            GregorianCalendar cal2 = new GregorianCalendar(date2.getYear(),date2.getMonth(),date2.getDate());
            
            //long difms = (cal2.getTimeInMillis()*(-1)) - cal.getTimeInMillis();
            
            long difms = cal2.getTimeInMillis() - cal.getTimeInMillis();
            long difd = difms / (1000 * 60 * 60 * 24 * 7);
            return difd;
        } catch (Exception ex) {
            ex.printStackTrace();
            Elemento.log.error("Excepcion al calcular los dias pagados: ",ex );
            return -1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nominas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antiguedad;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidadHorasExtra;
    private javax.swing.JCheckBox deduccionesBox;
    private javax.swing.JTextField descuentoIncapacidad;
    private javax.swing.JTextField dias;
    private javax.swing.JTextField diasIncapacidad;
    private com.toedter.calendar.JDateChooser fechaFinalPago;
    private com.toedter.calendar.JDateChooser fechaInicialPago;
    private com.toedter.calendar.JDateChooser fechaPago;
    private javax.swing.JButton guardar;
    private javax.swing.JCheckBox horasExtra;
    private javax.swing.JTextField importePagado;
    private javax.swing.JCheckBox incapacidad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRfc;
    private javax.swing.JTextField numDiasPagados;
    private javax.swing.JTextField numEmpleado;
    private javax.swing.JCheckBox percepcionesBox;
    private javax.swing.JComboBox tipoHoras;
    private javax.swing.JComboBox tipoIncapacidad;
    private javax.swing.JComboBox tipoRegimen;
    private javax.swing.JButton verDeducciones;
    private javax.swing.JButton verPercepciones;
    // End of variables declaration//GEN-END:variables
}
